name: "CI/CD Pipeline for Cobra"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-pipeline:
    uses: guillipa1993/devops-pipelines-ci-cd/.github/workflows/go-ci.yml@main
    secrets:
      token: "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"
    with:
      go-version: "1.18"

# Cambio para activar el job