name: CI/CD Pipeline for Cobra

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-pipeline:
    uses: guillipa1993/devops-pipelines-ci-cd/.github/workflows/go-ci.yml@main
    with:
      go-version: '1.18'  # Personaliza la versión de Go si es necesario