name: "CI-CD Pipeline for Cobra" # Nombre del workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-pipeline:
    uses: guillipa1993/devops-pipelines-ci-cd/.github/workflows/go-ci.yml@main
    with:
      go-version: "1.18"
